dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: JYpyIxxn2Rf8ybg11qds6Ir85M2EBN1t2lE8H8mOM0Ej6qWSiY+uVBZKjHyAYg03SCnMz5ePV5cMPO8UAWmm7XJETHwW1zvCSphklQgLg42u7wFBna4lhtNTkVX0Q75ncXYoUNkVlMAIn1ZcHo41zrODIjj3JPEKfzweJqnUisTveHSk4D3wg2vdSyy6ZwJR0n8VgqYFjJExRJEE8d/9z3oDyvv2jFxW9WSnQbvETcbtdHUZSS/glNap8n4rRzF5mNhiGjvaLrUkPbmboc7HQusCA1SGn4O1Y6DqHuPEm0OqYdq6z6kBjH6gdArnn9aOfPAkk5UAPm1hUcBr9Bmt9ICbf9EnMRZdfeD90dUKUVNEglQVkJv2CDbJDg0LYR9pYxIt9mqIy/yQAqcRyd29yDgrBroc8dvOKGHX8HFrgSxI/dPKlSujfMwJRpNyxuXwXTBFCRVzTr1/fGD6QbHUAIowwPXaZKw4rHpZUpqa+wv64j3P4PLin4gd79pHmxlvDeJcjH/bZt0V7nR7k+NF66zH8SKqpwm5wG0cwZAg9GS6GSpsfPM4UibcdYfRtfpq8Fdtm32CXRMM9q0agfHdwsgPp4Ca7vYLQI0glm8THb2i4B6252auS/HzCahnE/jBXnMjKHpeQj1B1Jn3nIGe+a41WnCzL967HM7VBYoZKxg=
